[package]

name = "handlebars-iron"
version = "0.8.2"
authors = ["Ning Sun <sunng@about.me>"]
description = "Handlebars templating middleware for Iron."
license = "MIT"
keywords = ["handlebars", "templating", "web", "webdev", "iron"]
homepage = "https://github.com/sunng87/handlebars-iron"
repository = "https://github.com/sunng87/handlebars-iron"
documentation = "http://sunng.info/handlebars-iron/"
readme = "README.md"

[dependencies]

iron = "^0.1.20"
handlebars = "^0.9.2"
rustc-serialize = "^0.3.15"
plugin = "^0.2.6"
walker = "^1.0"
notify = { version = "^2.3", optional = true }
log = "*"

[features]
default = []
watch = ["notify"]
